CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# DEBUG
CONFIG_ZMK_USB_LOGGING=n

# KEYBOARD NAME
CONFIG_ZMK_KEYBOARD_NAME="TBKmini_isaac"

# SLEEP
# CONFIG_ZMK_IDLE_TIMEOUT=10800000
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=10800000

# MOUSE
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_POINTING=y
